### PR TITLE
Feature/8.x

### PR DESCRIPTION
**Pull request by derhecht**
Version 5.2 with TYPO3 8.7 support
**Composer-only-version!**
see ReadMe.md

### CODE REVIEW

**Comment by derhecht** [comment]
@SvenJuergens may have a look and approve

**Comment by SvenJuergens** [comment]
@derhecht hi, great work :+1: 
but i think composer-only is one step too much. This breaks every compatibility to a former version of phpmyadmin.I think this is at least a 6.0 version or a complete standalone fork. Just my 2 cents, the final decision lies with mehrwert :)

**Comment by simonschaufi** [comment]
This is way too complicated even just for composer. I basically just want to require this package and don't care about anything else. No additional shell scripts...

**Comment by derhecht** [comment]
of course normally I would do the same but phpmyadmin make it impossible todo so right now as it needs a make-project command itself :(

**Comment by williamdes** [comment]
maybe this PR can be closed ?

**Comment by derhecht** [comment]
> maybe this PR can be closed ?

feel free.

**Comment by williamdes** [comment]
> > maybe this PR can be closed ?
> 
> feel free.

Please do it ;)
I am not a maintainer

**Comment by williamdes** [comment]
Or maybe update it ?
From my phpMyAdmin team member point of view using composer version is a good idea

**Pull request closed without merging**
